### ISSUE TITLE
events offset by minTime in timelineWeek view

### ISSUE THREAD

**Issue by psnfrench** [fullcalendar/fullcalendar-scheduler#151] opened 2016-03-29 23:04 UTC
With the minTime specified, viewing in timelineWeek with a slot duration of 1 day offsets the event by the minTime to the left. without the minTime option, events are positioned correctly.

http://jsbin.com/jifiye/edit?js,output

**Comment by mrship** [comment] 2016-03-31 15:38
We are also seeing this but held off reporting because we didn't have the time to prepare the JS Bin - thanks for your efforts!

**Comment by psnfrench** [comment] 2016-03-31 21:53
I dug into this a bit, and I made the following hack as a workaround which fixes the problem for me.

On line 2731 of scehuler.js change this:

this.start = this.normalizeGridDate(this.start).add(this.minTime);

to:

if (computeIntervalUnit(this.labelInterval) === "hour") {
	this.start = this.normalizeGridDate(this.start).add(this.minTime);
} else {
	this.start = this.normalizeGridDate(this.start);
}

i.e. only add the minTime if the interval is in hours. I'm sure this is not 100% robust, but it works for me in the mean time.

**Comment by arshaw** [comment] 2016-04-14 12:25
confirmed. the workaround is to set `minTime` and `maxTime` in view-specific options that only apply to the view that displays hours.

**Comment by arshaw** [comment] 2016-05-02 05:39
the fix for this was released in v.1.3.1
https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.3.1
thanks!

**Closed by arshaw** 2016-05-02 05:39 UTC
Labels: Status-Confirmed
