### ISSUE TITLE
Dragging event with multiple resourceIds removes second resourceId

### ISSUE THREAD

**Issue by toxaq** [fullcalendar/fullcalendar-scheduler#208] opened 2016-08-27 21:33 UTC
Drag either representation of the event to another column. The alternate representation disappears.

http://jsbin.com/noliye/edit?html,output

I'm not sure what is intended to happen here. I'm looking at a task that is shared. If one person is unable to do that task, I want to assign it to someone else. This would remove it form both people.

**Comment by arshaw** [comment] 2016-09-01 22:56
thanks for the report. this seems to be a duplicate of:
https://github.com/fullcalendar/fullcalendar-scheduler/issues/111
&uarr;
Could you please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

**Closed by arshaw** 2016-09-01 22:56 UTC

**Comment by toxaq** [comment] 2016-09-01 23:10
No problem, I didn't find #111 in my searches.
