### ISSUE TITLE
Time bar issues

### ISSUE THREAD

**Issue by skogsharald** [fullcalendar/fullcalendar-scheduler#25] opened 2015-09-17 08:09 UTC
I am having issues with the time bar not being rendered properly in Scheduler v1.0.0. Attached are two screenshots illustrating my issue.

![screen shot 2015-09-17 at 09 56 56](https://cloud.githubusercontent.com/assets/2445506/9927899/7a5794f6-5d22-11e5-9758-c4cb342287f3.png)
![screen shot 2015-09-17 at 09 58 54](https://cloud.githubusercontent.com/assets/2445506/9927948/be69240c-5d22-11e5-8c4e-5dbad030af3d.png)

In the first image, you can see the time bar starting at 00:00, but the scroll bar for the timeline being somewhere about 1/4 into the day. In the second image, you can see the time bar starting at 06:00 and the time bar being in the same spot as the previous image. It seems this happens every second day, because when I go to September 20th, the time bar starts at 00:00 again, but at 06:00 on the 21st.

If I use the scroll bar to scroll in the view, the times are rendered properly and follow along nicely, attached is another image of the timeline for September 18th, only scrolled a little bit to the left. As shown, the times are now rendered properly.
![screen shot 2015-09-17 at 10 04 11](https://cloud.githubusercontent.com/assets/2445506/9928067/8ec11d62-5d23-11e5-89e8-b88c8c0b8c3b.png)

I tried rolling back to the beta version of the scheduler I downloaded this summer (switched out both fullcalendar and scheduler files) and the times are rendered properly there with no issues, but there seems to be something off in the 1.0.0 version of Scheduler.

The code used is just basic resource retrieval from an API and everything is rendered using Fullcalendars and Schedulers default renderers. I am reluctant to post the code publicly, however, as it is intended to be used as a commercial product (with a license being purchased as soon as we are ready to roll out of beta), but I can supply you with my code privately if necessary.

**Comment by eybarta** [comment] 2015-09-20 09:17
I think I might come across a related issue: timeline not synced with scrollbar.
When moving scrollbar, the timeline would jump into place..
I resolved this issue (at least seems to be resolved) with a minor change in the scheduler code.. if you look at the unminified version around line > 2071, there's 2 calls to resetScroll:
2071: //resetScroll(); <<--- comment this out
2072: setTimeout(resetScroll, 0);

I'm still not sure why both are needed, but for me commenting out the first solved the problem. It's worth a try, see if it solves your issue also.

**Comment by arshaw** [comment] 2015-10-10 22:06
hmmm curious. what browser are you using?

also, if you have time, could you post the config settings you are using? preferably via jsbin, new instructions for scheduler debugging template: http://fullcalendar.io/wiki/Reporting-Bugs/

**Comment by eybarta** [comment] 2015-10-11 13:07
Starting off with your jsbin: http://jsbin.com/jufena/1/edit?js,output

I only changed 1 setting:
now: moment()

So the calendar will always scroll to current time..

http://jsbin.com/qafozepagu/edit?js,output

try moving to the next day, you should see the timeline loose synce with the scrollbar,
if you move the scrollbar a bit, it will jump back into place.. If you can't reproduce,
try scrolling to end of the day and click next day again..

**Comment by arshaw** [comment] 2015-10-11 15:36
thanks for the recreation! what browser are you using? i ask because many browsers handle the initial scroll state different (Firefox for example)

**Comment by arshaw** [comment] 2015-10-11 15:36
and on what OS

**Comment by skogsharald** [comment] 2015-10-11 20:58
Thanks for creating that JSBin! It is exactly the issue I am experiencing. I the problem persists using Chrome on both OSX and Windows and when using IE, but not Firefox on both OS's.

**Comment by eybarta** [comment] 2015-10-12 04:29
I'm using chrome on windows.

**Closed** 2015-10-13 03:34 UTC
Labels: Status-Confirmed

**Comment by arshaw** [comment] 2015-10-13 04:13
fixed in v1.0.1
http://jsbin.com/sugihu/1/edit?html,output

**Comment by skogsharald** [comment] 2015-10-13 06:57
Thank you!
