### ISSUE TITLE
Bug while dynamically adding resource in "agendaWeek" view

### ISSUE THREAD

**Issue by mstoelzle** [fullcalendar/fullcalendar-scheduler#170] opened 2016-05-13 11:05 UTC
Hi,
I found a bug which was introduced with the v1.3 of the scheduler plugin:
If you add a new resource dynamically while being in the "agendaWeek" view and then change the view to for example the "three day" view, the view is empty (without any events and resources).
You can reproduce it either with your scheduler demo or a standard jsbin:

http://fullcalendar.io/js/fullcalendar-scheduler-1.3.1/demos/dynamic-add-remove.html
OR
http://jsbin.com/benaropoqi/edit?js,output

Best regards,
Maximilian

**Comment by Rubenvanhoeyveld** [comment] 2016-05-26 22:13
Also struggling with this... I was looking for a way to toggle the visibility of a resource. I tried to remove and add resources, but not all views seem to get the changes.

**Comment by arshaw** [comment] 2016-05-29 01:23
@mstoelzle i tried reproducing but it works every time for me.

i am going to the "week" button (which is agendaWeek), adding a resource via the "+resource" button, then going to "3 day" and everything shows up fine.

what browser are you using? could you post a screencast?

**Comment by arshaw** [comment] 2016-05-29 01:39
i was able to recreate. realizing this is a duplicate of:
#179
&uarr;
Visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by arshaw** 2016-05-29 01:39 UTC
Labels: Status-Reproducing
