### ISSUE TITLE
Resource constraint

### ISSUE THREAD

**Issue by sulian** [fullcalendar/fullcalendar-scheduler#108] opened 2016-01-12 09:08 UTC
Suppose you have a room that can not be reserved the morning (but others rooms can), is it possible to restrain resource for a couples of hours or a day (week-end) ?
It will be interesting if you can limit for a resource only or for the parent of resources (all rooms for batiment A for example).

Sorry again for my poor english.
Sulian

**Comment by espen** [comment] 2016-01-14 15:29
@sulian see http://fullcalendar.io/docs/display/businessHours/. And if you have any further questions please see http://fullcalendar.io/support/

**Comment by sulian** [comment] 2016-01-14 15:53
Thanks @espen but  BusinessHour is a global option, it cannot work with resources.

For my example, I have a room A that cannot be reserved from 8:00 until 12:00 but room B & C can be.

It seems that my request is like the #61 issue : "businessHours per-resource"

**Comment by arshaw** [comment] 2016-01-15 04:23
you'll want to use `eventConstraint` http://fullcalendar.io/docs/event_ui/eventConstraint/

i'm not sure whether your allowed to put a `resourceId` in the eventConstraint object, I'd have to check. (I'll leave this issue as "discussing" because still need to get to the bottom of this)

if that doesn't work, might want to create separate background events, all with the same event ID's, and then set the eventConstraint to that ID.

**Comment by sulian** [comment] 2016-01-15 10:41
I understand. I think "Resource limitation" and you "Event constrain" but the use of background event in order to limit the availability of a resource is ok for me.

**Comment by arshaw** [comment] 2016-04-28 06:36
duplicate of #50. i will write more on that issue right now...

**Closed by arshaw** 2016-04-28 06:36 UTC
Labels: Status-Discussing
