### ISSUE TITLE
Vertical Resource View

### ISSUE THREAD

**Issue by philipstratford** [fullcalendar/fullcalendar-scheduler#5] opened 2015-08-21 08:47 UTC
I apologise is this is already possible and documented somewhere, but I can't find it. However, what I'd really like is something basically the same as the Timeline view in the Scheduler add-on (which I'm very happy to pay for, all of your work is excellent), but with the resources as columns and the timeline going vertically down the page. So, exactly the same as the week view, really, but with days/dates in column headings replaced with resource names.

**Comment by espen** [comment] 2015-08-24 13:19
You mean like what is described under "What’s left to be done" here: http://blog.arshaw.com/1/post/2015/08/scheduler-released.html

**Comment by philipstratford** [comment] 2015-08-24 13:28
Er... Yeah! :/




On Mon, Aug 24, 2015 at 6:19 AM -0700, "Espen Antonsen" <notifications@github.com> wrote:
You mean like what is described under "What’s left to be done" here: http://blog.arshaw.com/1/post/2015/08/scheduler-released.html

---

**Comment by arshaw** [comment] 2015-08-26 03:32
We'll leave this issue open to represent the feature request specified in Google Code's [Issue 490](https://code.google.com/p/fullcalendar/issues/detail?id=490), which has since been close because Google Code is shutting down.

**Comment by Efiware** [comment] 2015-09-04 10:56
Hi
Any best guesses when this feature will be implemented? I'm looking for a calendar with this kind of view and would very much like to use (the commercial version of) FullCalendar.

**Comment by daxiez** [comment] 2015-09-07 08:26
Hi 
Is this feature currently being implemented? Looking forward to this very much...

**Comment by espen** [comment] 2015-09-07 10:20
@AndersBachLarsen "This feature is a top priority for Scheduler.". So it's coming. But no ETA announced. http://blog.arshaw.com/1/post/2015/08/scheduler-released.html

**Comment by oserra** [comment] 2015-09-24 15:06
The multiresource view (multiple columns per day) is very usefull for job assigning... i.e. you've got jobs that must be done, and technical people that must do it. Sometimes a job must be done by two or more people, so it would be great you include the option to, somehow, have events linked, so that two differents events (different Ids) share a parentID (jobId?).
So, when I move an event, the linked ones move at the same time.
Or maybe the json event object may include a list of resources, and that's the way they stay  alltogether aligned.

**Comment by espen** [comment] 2015-09-24 15:07
@oserra see https://github.com/fullcalendar/fullcalendar-scheduler/issues/13

**Comment by mlynch6** [comment] 2015-09-28 17:27
Looking forward to this feature very much.

**Comment by Rubenvanhoeyveld** [comment] 2015-10-30 14:04
Any idea when this will be implemented?

**Comment by mattdanna** [comment] 2015-11-01 22:00
+1

**Comment by arshaw** [comment] 2015-11-03 02:00
I'm making some pretty good progress with this. Will post a beta on Nov 16th.

**Comment by johans** [comment] 2015-11-03 07:41
Awsome news, keep up the good work!

**Comment by czillmann** [comment] 2015-11-03 08:21
Great to hear :)

**Comment by Rubenvanhoeyveld** [comment] 2015-11-03 08:25
Awesome!

**Comment by AndersBachLarsen** [comment] 2015-11-03 09:31
Great news!

**Comment by stephen-samra** [comment] 2015-11-03 12:20
Looking forward to this. Glad to hear it's making good progress!

**Comment by Patatou** [comment] 2015-11-03 13:59
Awesome !

**Comment by Efiware** [comment] 2015-11-03 18:30
This is indeed great news!

**Comment by jeremymcminn** [comment] 2015-11-10 08:23
Looking forward to this - haven't been able to find a stable fork with all the features the latest version of Fullcalendar has, so this will be an absolute lifesaver!

**Comment by arshaw** [comment] 2015-11-16 01:38
The beta version of this feature has been release ([v1.1.0-beta](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.1.0-beta)).

Demo: [agenda-views.html](http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0-beta/demos/agenda-views.html)
Download: [fullcalendar-scheduler-1.1.0-beta.zip](https://github.com/fullcalendar/fullcalendar-scheduler/releases/download/v1.1.0-beta/fullcalendar-scheduler-1.1.0-beta.zip)

Please give it a try and report any bugs or feature requests on this ticket!

**Comment by arshaw** [comment] 2015-11-16 01:58
This beta release is licensed solely under a [Creative Commons Non-Commercial license](https://creativecommons.org/licenses/by-nc-nd/4.0/) for demo purposes only. This *Vertical Resource View* feature will eventually be bundled with an official release of FullCalendar Scheduler. As a reminder, Scheduler has different [licensing terms](http://fullcalendar.io/scheduler/license/) than the main FullCalendar project. When v1.1.0 of Scheduler is released, the paid commercial license will retain the same [pricing](http://fullcalendar.io/scheduler/purchase/).

**Comment by ari** [comment] 2015-11-16 02:36
Very interesting, thanks. I'm unfamiliar with the CC license for software (I've typically seen it for images, documentation, etc). How does this work for open source projects using your library? What is the intersection between the CC license you chose and the GPL for example?

Thanks for all your excellent work.

**Comment by Efiware** [comment] 2015-11-16 05:29
Looks very nice. Is it possible to show a full week in one column, i.e. let the time-axis span a full week?

**Comment by Patatou** [comment] 2015-11-16 07:12
Ty for this great work.

But, i'm a little disapointed by this version. In fact, I think (or hope :) ) that everyone want this vertical version : 
------DAY #1 -----||||||---------- DAY #2 --------||||||| --------DAY #3 
A-- R1 | R2 | R3-||||||-------R1 | R2 | R3-------|||||||----R1 | R2 | R3
X
I 
S

Does it possible to have this view ? (Just inverse ressource and day in your version)

Ty

**Comment by jeremymcminn** [comment] 2015-11-16 07:55
Brilliant stuff - thanks for all your hard work

**Comment by Rubenvanhoeyveld** [comment] 2015-11-16 08:00
Great work, @arshaw! When do you think this will be released as stable?

**Comment by Rubenvanhoeyveld** [comment] 2015-11-16 08:37
@Patatou, check the demo code...

This might be what you need:

		views: {
			agendaTwoDay: {
				type: 'agenda',
				duration: { days: 2 },

				// views that are more than a day will NOT do this behavior by default
				// so, we need to explicitly enable it
				groupByResource: true

				//// uncomment this line to group by day FIRST with resources underneath
				//groupByDateAndResource: true
			}
		},

Set the `groupByDateAndResource` to `true` :+1:

**Comment by Patatou** [comment] 2015-11-16 08:41
OMG ! You're brillant ! :+1:

**Comment by jeremymcminn** [comment] 2015-11-16 08:59
There seems to be an issue on dayClick

    dayClick: function(date, jsEvent, view, resourceObj) {
            console.log(date);
            console.log(jsEvent);
            console.log(view);
            console.log(resourceObj);
    },

Both date and resourceObj parameters are coming back as undefined.

**Comment by philipstratford** [comment] 2015-11-16 09:30
This is excellent, thanks for all your hard work, Adam!

**Comment by jdriesen** [comment] 2015-11-16 10:48
Wow ...great stuff !
Unfort. I'm having the same issue as jeremymcminn ...

**Comment by jeremymcminn** [comment] 2015-11-16 14:41
Also business hours causes an error.    
    businessHours :  {
                start: '10:00', 
                end: '15:00',
                dow: [1,2,3,4,5,6,0],
    },

Uncaught TypeError: Cannot read property 'push' of undefined

**Comment by dc-dd** [comment] 2015-11-17 13:17
after instantiation:
```javascript
$('#calendar').fullCalendar('addResource', { id: 'e', title: 'Room E', eventColor: 'blue' });
```
Seems not to rerender the header, the resource isn't shown.

**Comment by jeremymcminn** [comment] 2015-11-18 23:23
Agreed with dc-dd, if background-event objects could also have a resourceId that would be brilliant!

Thanks for all your hard work on this Adam

**Comment by Patatou** [comment] 2015-11-19 09:11
Hmmm... can't test it for the moment.

I've change nothing in my code, except .js, and directly this error appear : 
Uncaught TypeError: Cannot read property 'prototype' of undefinedextend
 @ scheduler.js:17(anonymous function)
 @ scheduler.js:1882(anonymous function)
 @ scheduler.js:1932slice
 @ scheduler.js:12(anonymous function)
 @ scheduler.js:14

No error with old version (1.0.2)... omw...

**Comment by dc-dd** [comment] 2015-11-19 09:15
@Patatou : Do you use fullcalendar 2.5.0 beta? if not please try

**Comment by Patatou** [comment] 2015-11-19 09:16
Did'nt see this release, gonna try it immediately

**Comment by Patatou** [comment] 2015-11-19 09:21
<--- Dumb :)

Work fine with FC beta 2.5

Ty :kissing:

**Comment by Patatou** [comment] 2015-11-19 09:26
:'( 
This issue : https://github.com/fullcalendar/fullcalendar/issues/2892 still present... It's a big probleme (for me :) ) because can't display shceluder in vertical line with duration bigger than 3 days.

**Comment by teamsynced** [comment] 2015-11-19 22:52
This is awesome. Can we have an option to do days rather than times on the left vertical axis?

Thanks,
TL

**Comment by johans** [comment] 2015-11-20 06:26
Just wanted to confirm the same problem as @jeremymcminn reported above with the dayClick function.

**Comment by dc-dd** [comment] 2015-11-20 17:31
Is there a way to have a separate normal "agendaDay" and an "agendaDay" with resources?
Currently setting "resources" will transform the normal "agendaDay" (as also the "basicDay") into a resource view.

**Comment by arshaw** [comment] 2015-11-23 10:45
Many of these issues are now resolved!
Just released [v1.1.0-beta2](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.1.0-beta2).
Requires fullcalendar core [v2.5.0-beta2](https://github.com/fullcalendar/fullcalendar/releases/tag/v2.5.0-beta2).
[Demo](http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0-beta2/demos/agenda-views.html)

**Responses:**

@ari - there is no intersection between the CC and GPL licenses. you must chose one of them, and there is no overlap in terms. [more info](http://fullcalendar.io/scheduler/license/)

@jeremymcminn, @jdriesen, @johans - dayClick issue has been fixed

@jeremymcminn - businessHours issue has been fixed

@dc-dd - can you break down your issues and submit as separate tickets?

@dc-dd, @jeremymcminn - background events do accept a `resourceId`. should work.

@dc-dd - in response to your last comment, use `groupByResource` with [view-specific options](http://fullcalendar.io/docs/views/View-Specific-Options/).

**Comment by delx** [comment] 2015-11-23 12:16
@arshaw 

I think I found a bug when calling refetchResources. Calling refetchResources does not work the first time. The new resources do not show up. Strangely it works for subsequent refetchResources calls.

I used your [demo](http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0-beta2/demos/agenda-views.html) to reproduce the bug.

I changed the resources property to a function:

    resources: function(callback) {
        callback([{id: 'a', title: 'TIMESTAMP=' + Date.now()}]);
    },

Furthermore I added a button to test refetchResources:

    <a href="#" onclick="$('#calendar').fullCalendar('refetchResources');return false">Change resources</a>

I would appreciate a quick bugfix. Thanks in advance.

**Comment by jeremymcminn** [comment] 2015-11-23 12:23
@arshaw thank you for getting these fixes sorted so quick!  Looking forward to implementing this new view in my app

**Comment by dc-dd** [comment] 2015-11-23 14:34
@arshaw 
> @dc-dd - can you break down your issues and submit as separate tickets?

Currently "those empty Array for resources" issues are not reproducible any more with beta2.

Thanks there for.

But as @delx pointed out there are now other problems.

It seems they occur with each resources change. So calling "refetchResources" twice will produce an expected result - of course calling it twice is a not expected to do.

I put up a fiddle for demonstration purposes:
http://jsfiddle.net/1nyed0p3/2/

quick explanation:
- the button "refetchResources" will do a `$('#calendar').fullCalendar('refetchResources');`
- the checkbox "refetch twice", will do a 'refetchResources' twice when pressing that button
- the radios define the resources
  - "Empty" for empty resources
  - "A" for one resource of resourceId "a"
  - "B" for one resource of resourceId "b"
  - "A and B" for two columns of resourceId "a" and resourceId "b"

When running you will first see the result for empty resources, which is fine.
- check "A" and press "refetchResources" - _this produces an **unexpected behaviour**, the events shown are correct, but the **column header is not updated correctly**_
- press "refetchResources" again - _now also the column header is rendered correctly_

Any further change combinations have the same result, pressing "refetchResources" once doesn't update the header column correctly, it have to use "refetchResources" twice,
as also can be seen when checking "refetch twice", then "refetchResources" is called every time twice producing correct behaviour for events shown and rendered column headers.

**Comment by lizhou86** [comment] 2015-11-24 23:56
@arshaw 
Thanks for the great work. 
I just found an issue with "select" callback on week and month view (possibly because they are not in vertical resource display mode)

To reproduce In you demo:
http://fullcalendar.io/js/fullcalendar-scheduler-1.1.0-beta2/demos/agenda-views.html

Go to week or month view and try to do select and console output "Uncaught TypeError: Cannot read property 'resourceId' of undefined" and callback will not be fired.

Thanks!

**Comment by arshaw** [comment] 2015-11-25 04:52
good catch @lizhou86 :8ball:

**Comment by arshaw** [comment] 2015-12-01 04:59
This has been release in v1.1. Please enter any additional bugs or feature requests as separate tickets. Thanks!

http://fullcalendar.io/docs/vertical_resource_view/getting_started/
https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.1.0

**Closed by arshaw** 2015-12-01 04:59 UTC
Labels: Status-Accepted

**Comment by Hanamant-Kadlimatti** [comment] 2016-06-07 07:30
hi iam creating vertical resources in fullcalendar-scheduler its working fine but events are not coming.
help me.

**Comment by arshaw** [comment] 2016-06-08 04:01
hello @Hanamant-Kadlimatti this issue is closed. could you please proceed with following "Getting Help"
http://fullcalendar.io/support/

**Comment by Hanamant-Kadlimatti** [comment] 2016-06-08 05:02
Thank U  I will try it.
