### ISSUE TITLE
Paginate Resources: Add new resources and events to timeline without re-fetching everything

### ISSUE THREAD

**Issue by HemanthKona** [fullcalendar/fullcalendar-scheduler#181] opened 2016-06-01 01:14 UTC
Hi,
Firstly, I would like to appreciate the work you are doing on fullCalendar timeline, its outstanding.

Coming to the problem I'm trying to solve,
- I'm trying to render large number of resources on the timeline view 
- So I need a pagination mechanism which will dynamically add resources and events associated with it without re-rendering fullCalenadar or re-fetching all resources 
 
Here is the link to jsBin about what I'm trying to achieve. http://jsbin.com/reraye

In the Jsbin example, I have shown how I'm doing it currently, but it is slow to render them. It would be good to have a single method to add resources and events to the timeline at once without needing to reload everything.

Its similar to #12 or #46. Except only need to add 'new' resources and events to the calendar

Thanks

**Comment by arshaw** [comment] 2016-06-01 03:47
thanks for the thoughtful submission

i believe this is duplicate of
https://github.com/fullcalendar/fullcalendar-scheduler/issues/141
&uarr;
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates.

**Closed by arshaw** 2016-06-01 03:47 UTC

**Comment by HemanthKona** [comment] 2016-06-01 15:55
Thanks for the response. Looking forward for the pagination feature.

**Comment by setu1421** [comment] 2020-05-19 15:21
Is the pagination feature added in Full Calendar finally? I need the feature badly :(
