### ISSUE TITLE
bad performance: updateResource, for changing resource data and rerendering

### ISSUE THREAD

**Issue by bensmeets** [fullcalendar/fullcalendar-scheduler#68] opened 2015-11-16 13:33 UTC
We're using the scheduler in a context, where we almost exclusively add resources and events through .fullCalendar('addResource/removeResource') and .fullCalendar('renderEvent/removeEvents'). Just to be able to have full control over _what_ is rendered, _how_ and _when_.

We were just trying to implement an extra column for the resources, called "occupancy", just like in the examples. We found it hard to figure out a way to update the value of each "occupancy" field after initial "adding".

So we can do:

```
function renderOurCustomObject(object) {
  cal.fullCalendar('addResource', {
    id: object.id,
    title: object.complicated_name,
    occupancy: 0
    etc...
  });
}
```

But now, we want to change something like the example above, into a function that will _render_ when the resource is not there yet, and _update_ it when it is. E.g.:

```
function renderOurCustomObject(object) {
  var existing = cal.fullCalendar('getResourceByID', object.id);

  if (existing) {
    // Update occupancy to new value
    existing.occupancy = 100; // e.g.

    // Now this is where the problem lies. How can I tell the existing resource to re-render
    // and update all it's columns, without having to remove and re-add the entire resource?
   // Something like existing.render(); ?
  } else {
    // Render completely new resource
    cal.fullCalendar('addResource', {
      id: object.id,
      title: object.complicated_name,
      occupancy: 0
      etc...
    });
  }
}
```

Any solution is much appreciated :) Thanks.

edit: essentially, the exact same problem exists with updating the label of a rendered event, but that has the correct api for it http://fullcalendar.io/docs/event_data/updateEvent/

Tnx

**Comment by arshaw** [comment] 2015-11-20 01:45
i agree, there should be native support for this. right now, doing a `removeResource` followed by an `addResource` with the same data is your best bet

**Comment by blakedietz** [comment] 2017-02-21 16:29
Impacted Fullcalendar Version: v2.6.0

@arshaw: This may be a completely separate ticket, but since you're recommending `addResource` and `removeResource` to update events I want to add that adding/removing a small number of resources through `addResource` and `removeResource` is quite slow as it triggers a full calendar render for each resource in both methods. For example, adding and removing around 20 resources takes nearly 2.5 seconds per method in my case.

I ended up tracking the problem down using Chrome's flame graphs. The problem is that `addResource` eventually triggers `View.displayEvents` which is the most expensive call. If you want the cpu profile that I saved from dev tools I can shoot it your way.

Here's a screen capture of the flame graph.

![screen shot 2017-02-21 at 9 15 44 am 2](https://cloud.githubusercontent.com/assets/2549228/23173732/5eafaf9a-f817-11e6-909a-06b7ba059841.png)

Here's a cheap solution for the problem for `fullcalendar.js`:

```js
      ...
       t.isPerfMode = false;
       ...
	function perfMode(isPerfMode) {
            if (typeof isPerfMode == 'boolean') {
                t.isPerfMode = isPerfMode;
            }
        }

	function renderEvents() { // destroys old events if previously rendered
		if (!t.isPerfMode && elementVisible()) {
			freezeContentHeight();
			currentView.displayEvents(events);
			unfreezeContentHeight();
		}
	}
        ...
```

It's called similarly to `batchRows` and `unbatchRows` when looping over resources to add.

Any thoughts?

**Comment by arshaw** [comment] 2017-02-21 20:56
thanks @blakedietz for the detailed description of the problem. i did not realize these performance problems would happen. will take a look

**Comment by LeoFlandin** [comment] 2017-03-24 08:02
Hi, 

There a other thing to consider in favor to rapidly add the "updateResource" feature : 
When doing `removeResource` followed by `addResource`, the order is not respected. The last updated resource will be stacked at the bottom of the list.

**Comment by jujis008** [comment] 2017-05-25 07:29
got this issue as well, event not to much data, like 200 of records if you loops to change something will have bad performance.

**Comment by drake7707** [comment] 2017-10-03 11:32
I had the same issue with lots of addResource and removeResource calls.

I fixed it by adding a renderPaused property of the ResourceView:
```
ResourceViewMixin = {
   ...
  renderPaused: false
  ...
```
Then in the handleResourceAdd and handleResourceRemove of the ResourceView changed it to:
```
  handleResourceAdd: function (resource) {
      if(!this.renderPaused)
            return this.requestResourceRender(resource);
  },
  handleResourceRemove: function (resource) {
      if (!this.renderPaused)
            return this.requestResourceUnrender(resource);
  }
```

Then in my own code wrapped the add and removeresource calls with:
```
$("#cal").fullCalendar('getView').resourcePaused = true;
... // Do the updates
$("#cal").fullCalendar('getView').resourcePaused = false;
```
Now it still needs to actually render which I forced by clearing the current view and then changing it again:
```
 var currentView = $("#cal").fullCalendar('getView').name;
 $("#cal").data('fullCalendar').clearView();
 $("#cal").fullCalendar('changeView', currentView);
```
And now it loads instantly.

Note if you also use the agenda view you'll need to also add a renderpaused in the resetresources of that view:
```

View.prototype.resetResources = function (resources, eventsPayload) {
    if (!this.renderPaused) {
        this.startBatchRender();
        this.unsetResources();
        this.setResources(resources, eventsPayload);
        return this.stopBatchRender();
    }
};
```

**Comment by arshaw** [comment] 2019-07-30 02:37
wondering if this is still a problem in v4

**Comment by arshaw** [comment] 2019-07-30 19:51
probably not now that we have `batchRendering`. closing

**Closed by arshaw** 2019-07-30 19:51 UTC
Labels: Reproducing, Resource Rendering
