### ISSUE TITLE
How completely remove non business hours and continue event on next day

### ISSUE THREAD

**Issue by vahanpetrosyan** [fullcalendar/fullcalendar-scheduler#402] opened 2018-01-11 12:27 UTC
Hi all.
This is my calendar settings 

> $('#calendar').fullCalendar({
	........
	defaultTimedEventDuration:'02:00:00',
	events: planning_start,
	businessHours: {
            dow: [1, 2, 3, 4, 5], // Monday - Thursday
            start: '08:00',
            end: '20:00',
        },
	minTime: "08:00",
	maxTime: "20:00",
	.........
})

as example  if I add event on 10 hrs at 19:00 of some day it's show only an hour (19:00 - 20:00 because my maxTime is 20:00) and nothing on next day, but I need it to be continue from first business hour(08:00) of next work day.
Can you help me please?
How I can do that?
Best regards

**Comment by acerix** [comment] 2018-01-12 00:43
I'm not sure I understand your issue, would you be able to post a [runnable, stripped-down demonstration](http://fullcalendar.io/wiki/Reduced-Test-Cases/)?

You could set [nextDayThreshold](https://fullcalendar.io/docs/event_rendering/nextDayThreshold/) to '00:00:00' if the issue is events not showing on the next day when they end before 9:00.

**Comment by vahanpetrosyan** [comment] 2018-01-12 06:59
Hi Acerix. 
Thank you for fast reply.
OK let me send you more details.

>	$('#calendar').fullCalendar({
		editable: true, // enable draggable events
		droppable: true, // this allows things to be dropped onto the calendar
		header: {
			left: 'today prev,next',
			center: 'title',
			right: 'timelineWeek,month'
		},
		defaultView: 'timelineWeek',
		resourceLabelText: 'Manodopera',
		forceEventDuration:true,
		defaultTimedEventDuration:'02:00:00',
		resources: manodopera, 
		events: planning_start,
		defaultTimedEventDuration:'02:00:00',
		events: planning_start,
		businessHours: {
			dow: [1, 2, 3, 4, 5], // Monday - Thursday
			start: '08:00',
			end: '20:00',
		},
		
		..............
        
I'm using "timelineWeek" view and  if I'm not wrong "nextDayThreshold" not have affects for this view.
I removed minTime and maxTime parameters to make issue more visible.
Please look at screenshot.
https://s.nimbus.everhelper.me/share/1378990/7rp8a9m6dy45mky1gnc9
Now event continue on NON business hours too.
When I need break event on workday end and continue on next business hour(in screenshot Tue 1/9 - 8am)
Please look at screenshot.
https://s.nimbus.everhelper.me/share/1379048/86uckr0fi49qbg4te46k

**Comment by acerix** [comment] 2018-01-13 20:17
Thanks for the details and screenshot.

Would it work to specify multiple time ranges for each event like this example?

https://codepen.io/anon/pen/KZeERa?editors=0010

The two event entries are treated as one repeating event, since they have the same ID.

Or are you looking for a new feature that would only show events during business hours?

**Comment by vahanpetrosyan** [comment] 2018-01-14 10:35
Thanks for suggestion, but unfortunately repeating event with the same ID is not solve my problem.
In my calendar I have draggable events with "duration" option.
And I need the future to move and place it at any business hour and ignore all non business hours.

**Comment by Delfins** [comment] 2018-01-16 09:56
@acerix seems we are still far from solving the issue. What we are asking it's not something weird I guess: if I set business hours from 8am to 8pm (meaning 12 hours of working day), and I have an event that last 15 hours , if I set the event to start 8am of Morning, I expect Scheduler will automatically set the end of this event at 11am of Thursday. This is not happening: Scheduler sets the end of the event at 11pm Monday. You understand this is nonsense. So, would be highly appreciated if you can find a solution or apply a fix for this "logical" lackness of the library.

**Comment by acerix** [comment] 2018-01-17 01:18
I understand what you are looking for, but can't think of an easy way to achieve that.  Events are defined with a start and end time (not a duration) so in your example, it would be up to you to set the end time based on the duration excluding non-business hours, and to update it if the event is moved or resized.

To have the events not show during business hours, you could use repeating events for the segments which are in business hours, and update them in the `eventRender` callback if the event is dragged.

We could look info adding a new feature so only business hours are counted in calculations, etc. but currently the `businessHours` option is only used to emphasize time slots:

https://fullcalendar.io/docs/display/businessHours/

**Comment by vahanpetrosyan** [comment] 2018-01-18 12:00
OK got it @acerix  thank you.
Other question is that possible dynamically change "duration" or "end date" of event in "eventDragStart" callback?
When I use ` $('#calendar').fullCalendar('updateEvent', event); `I receive error.
Thanks

**Comment by acerix** [comment] 2018-01-19 04:39
Is it the same error as in this issue?

https://github.com/fullcalendar/fullcalendar/issues/3971
↑
Please visit the link, **give a** 👍  **to vote** ([?](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments)), press the 🔈**Subscribe** button to receive updates?

Otherwise please submit a new issue with a [runnable, stripped-down demonstration of the bug](http://fullcalendar.io/wiki/Reduced-Test-Cases/), if possible.

**Closed by acerix** 2018-01-19 04:39 UTC
