### ISSUE TITLE
Timeline Non-Business days without styles

### ISSUE THREAD

**Issue by agapas** [fullcalendar/fullcalendar-scheduler#109] opened 2016-01-12 16:07 UTC
The timeline view doesn't show the style for non-business hours/days (grey color) when the current page of the timeline only has non-business days.

Example: http://jsbin.com/fabejisabu/4/edit?js,output

Thanks!!

**Comment by arshaw** [comment] 2016-01-15 04:00
it's not displaying anything because your `businessHours` definition is out of spec.. should only have *times* as start/end

**Comment by agapas** [comment] 2016-01-18 10:50
I've changed the businessHours to use time but the problem with the styles is still there. 
You can see that the first "page" shows non-working days without applying the proper background color. If you go to the previous "page", you will see that Friday appears completely "grey". 

Example: http://jsbin.com/xucuguzavo/1/edit?js,output

If I switch to a different view (week, month), the non-working days appear with background color "grey".  Shouldn't it be the same in the timeline view?

Thanks!

**Comment by arshaw** [comment] 2016-01-20 09:31
reproduced, thanks!

**Comment by arshaw** [comment] 2016-07-19 08:23
seems to be the same bug as this one: https://github.com/fullcalendar/fullcalendar/issues/2944
(on core)

**Comment by arshaw** [comment] 2016-07-31 23:47
this has been fixed and released in v1.3.3

**Closed by arshaw** 2016-07-31 23:47 UTC
Labels: Business Hours, Code Complete, Confirmed
