### ISSUE TITLE
press-and-hold time range selection

### ISSUE THREAD

**Issue by gdolenc** [fullcalendar/fullcalendar-scheduler#154] opened 2016-04-07 08:13 UTC
Hi,

I am having problem with press-and-hold time range selection. I can only select one time slot via mobile device, but am not able to select two or more time slots by press and hold.

http://www.slotenis.si/rezervacije1/?lid=2

**Comment by arshaw** [comment] 2016-04-14 12:30
I'm looking at your demo on *desktop* and noticing that you can't even select timeslots with your mouse at all. This indicates to me that `selectable:true` has not been added. Could you check that?

**Comment by gdolenc** [comment] 2016-04-14 13:37
Yes, I have set the selectable to true. However, I require the user to be logged in, otherwise selectable is set to false. So, It will only work if login first. 

http://www.slotenis.si/wp-login.php

You can user the following login data:
Username: testuser
Password: testuser

After login, just proceed to http://www.slotenis.si/rezervacije1/?lid=2

**Comment by arshaw** [comment] 2016-04-20 04:35
I opened your demo up on the following:

```
iPad (4th generation, late 2012)
iOS 8.2
Mobile Safari 8

Galaxy Tab A
Android version 5.0.2
Chrome version 49.0.2623.105
``

and was unable to reproduce the problem. After doing a long tap, I was able to get the range selection to show up every time.

Could you please post your device/os/browser info? If possible, could you post a video? Where exactly do you need to tap-hold on the calendar to reproduce the problem?

**Comment by arshaw** [comment] 2016-04-20 04:36
Closing until further reproduction info is given

**Closed by arshaw** 2016-04-20 04:36 UTC
Labels: Status-Reproducing, Touch
