### ISSUE TITLE
Resources get double/triple/... when pressing next/prev button

### ISSUE THREAD

**Issue by aidistan** [fullcalendar/fullcalendar-scheduler#380] opened 2017-11-09 16:01 UTC
Resources get double/triple/... when pressing next/prev button. Test cases are here:
- The official demo: https://fullcalendar.io/js/fullcalendar-scheduler-1.8.1/demos/column-grouping.html
- My CodePen demo: https://codepen.io/aidistan/pen/ZaLrRz

**Comment by arshaw** [comment] 2017-11-13 04:10
confirmed. will get this fixed asap. looks like it's only happening for resource column grouping.

**Comment by arshaw** [comment] 2017-11-14 00:26
Released in core [v3.7.0](https://github.com/fullcalendar/fullcalendar/releases/tag/v3.7.0) and scheduler [v1.9.0](https://github.com/fullcalendar/fullcalendar-scheduler/releases/tag/v1.9.0).

**Closed by arshaw** 2017-11-14 00:26 UTC
Labels: Confirmed, View Rendering
