### ISSUE TITLE
clarity on disabling resources, esp per-view

### ISSUE THREAD

**Issue by danielsmacdonald** [fullcalendar/fullcalendar-scheduler#145] opened 2016-03-10 11:46 UTC
Currently, if you have a resource list in your FC options, day and agendaDay become "vertical resource views".

If you want to be able to have options for both resource and non-resource views, you are unable to do so. For example:

      header: {
           right: 'month,agendaWeek,agendaDay timelineDay'
      },
      resources: {...

There does not seem to be a way to keep agendaDay a non-resource view.

**Comment by arshaw** [comment] 2016-03-11 05:43
you could make a [custom view](http://fullcalendar.io/docs/views/Custom_Views/) with `type: "agendaDay"`, in combination with `resources: false`

**Comment by danielsmacdonald** [comment] 2016-03-15 15:51
Ok, thanks. Could this be added to the documentation somewhere? Maybe in [View Object](http://fullcalendar.io/docs/views/View_Object/)?

**Comment by arshaw** [comment] 2016-03-16 08:46
I'll make a TODO to improve the docs in this regard. thanks

**Comment by arshaw** [comment] 2016-04-14 12:41
this is actually a duplicate of https://github.com/fullcalendar/fullcalendar-scheduler/issues/115

closing

**Closed by arshaw** 2016-04-14 12:41 UTC
Labels: Docs, Status-Accepted
