### ISSUE TITLE
External Event Overlap

### ISSUE THREAD

**Issue by stillfire** [fullcalendar/fullcalendar-scheduler#72] opened 2015-11-23 15:54 UTC
Hi, I wrote on another issue, but I don't think this is related to where I posted ( https://github.com/fullcalendar/fullcalendar-scheduler/issues/24 )

When dragging external events onto the calendar in schedule view, overlap: false has no effect neither does eventOverlap:false
    
    $('#external-events .fc-event').each(function() {
            $(this).data('event', {
                title: $.trim($(this).text()), 
                stick: true, 
                eventOverlap: false,
                overlap: false // HAS NO EFFECT - WORKS IN FULLCALENDAR BUT NOT SCHEDULER

            });
            $(this).draggable({
                zIndex: 999,
                revert: true,  
                revertDuration:
            });
        });

**Comment by arshaw** [comment] 2015-11-25 04:47
most likely a duplicate of #24. could you read my latest comments on that issue and try the fix?

**Comment by stillfire** [comment] 2015-11-26 22:05
I downloaded the new beta versions and the external events are able to overlap on resources when dragging them into the calendar.

**Comment by arshaw** [comment] 2015-11-27 20:57
Could you try to post a JSBin of this? (http://fullcalendar.io/wiki/Reporting-Bugs/) Will help me save time as I'm trying to get a new release out by monday.

**Comment by stillfire** [comment] 2015-11-30 21:38
Here is the js bin.

Cheers!

http://jsbin.com/wacugoj/edit?html,js,output

**Comment by pratikdhaboo** [comment] 2015-12-03 05:02
I am also having the same problem, confirm the findings as replicated in JS Bin. Dragging an external event doesn't seem to honor eventoverlap setting.

**Comment by arshaw** [comment] 2015-12-29 08:33
i can confirm. and this also affects agenda/basic views. merely having the scheduler JS plugin loaded

**Closed** 2016-01-04 09:51 UTC
Labels: Status-Confirmed

**Comment by stillfire** [comment] 2016-01-06 18:48
Hey, I installed the new dist files and now I'm getting an error.

    TypeError: this.coordMap is undefined

**Comment by arshaw** [comment] 2016-01-07 11:41
fixed in scheduler 1.2.0 / core 2.6.0 , released

**Comment by arshaw** [comment] 2016-01-12 07:07
@stillfire you'll need to have the newest Scheduler code AND core code (fullcalendar.js and fullcalendar.css)

**Comment by stillfire** [comment] 2016-01-12 17:13
Thanks, I can confirm the problem is fixed.
